# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



School.create(name: "test", location: "7.917793,27.596054")
School.create(name: "test2", location: "8.515836,30.935898")
School.create(name: "test2", location: "8.515836,27.486191")
School.create(name: "test2", location: "5.397273,32.408066")
School.create(name: "test2", location: "6.125836,29.343398")
School.create(name: "test2", location: "9.795678,32.792587")


Staff.create(name: "Subin", role: "Headmaster",school_id:"1")
Staff.create(name: "Nafy", role: "Teacher",school_id:"1")
Staff.create(name: "Samir", role: "Teacher",school_id:"1")
Staff.create(name: "Mohammed", role: "Teacher",school_id:"1")

Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")
Resource.create(name: "Supplies", image_url: "http://www.inboundlogistics.com/cms/userfiles/0710_casebook-aid.jpg")
Resource.create(name: "School in a Box", image_url: "http://www.unicef.ie/schoolinabox/images/large/school_box2-L.jpg")
Resource.create(name: "Water", image_url: "http://geneva.usmission.gov/wp-content/uploads/2011/03/0331JapanRescue.jpg")
Resource.create(name: "Food", image_url: "http://en.trend.az/article_photo/2010/06/16/aid-kirgiz.jpg")
Resource.create(name: "First Aid", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTdiDD6vRLyLMI86pj-lXTZtFYZWOXiW3GyP7N8qAvg_FBAA-F")
Resource.create(name: "Sanitary Napkins", image_url: "http://unhcr.org/thumb1/50d185476.jpg")
Resource.create(name: "Rice", image_url: "http://farm5.static.flickr.com/4112/5036572184_5fa5d1ef3b.jpg")
Resource.create(name: "Medical Supplies", image_url: "http://www.b92.net/news/pics/2012/04/30/3752303904f9e6ef924b98873130518_v4big.jpg")
Resource.create(name: "Supplies", image_url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQLpJaACWnKTwVtxn5h5EHiGnPnafz36xASBtW2M6xbD-qOrELk")


Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")
Request.create(name: "Morbe", image_url: "http://www.theniles.org/media/articles/2012_10_04_Aping_Morbe.jpg")
Request.create(name: "Konga", image_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZYgKt2oK6CvFa9n32tbZnofO3ReljImZRzDrfsRvX1Mw7pG9nAQ")
Request.create(name: "Abyei", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSEc0F0pcUIXcj8L5wArus3vzER2INUMxKjm1jDCEBJOEpI7g47")
Request.create(name: "Machar", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQazuG01NNp75b35jfVsoESAtTiRCFZSxv1Tq5x1Vb4QNzq3S3-")